import { expect, test } from '@playwright/test'
import { mockBackend, signIn } from './mock.ts'
import type { TeacherAccount, TeacherMutation } from '../../src/types/app.ts'

const teacherId = '20000000-0000-0000-0000-000000000009'

test('administrator manages a teacher from the directory and dedicated page', async ({ page }, info) => {
  await mockBackend(page, { role: 'admin' })
  const accounts: TeacherAccount[] = []
  const requests: TeacherMutation[] = []
  const reports: Record<string, unknown>[] = []
  await page.route('**/rest/v1/rpc/admin_teachers', route => route.fulfill({ json: { total: accounts.length, rows: accounts } }))
  await page.route('**/rest/v1/rpc/admin_teacher', route => {
    expect(route.request().postDataJSON()).toEqual({ p_id: teacherId })
    return route.fulfill({ json: accounts[0] })
  })
  await page.route('**/rest/v1/rpc/admin_teacher_report', route => {
    reports.push(route.request().postDataJSON())
    return route.fulfill({ json: { as_of: '2026-09-14T11:30:00Z', page: 0, page_size: 25, rows: [], totals: { expected: 0, on_time: 0, late: 0, absent: 0, missing_exit: 0, completed: 0 } } })
  })
  await page.route('**/functions/v1/admin-teachers', async route => {
    const input = route.request().postDataJSON() as TeacherMutation
    requests.push(input)
    if (input.action === 'create') accounts.push({ id: teacherId, full_name: input.full_name!, cedula: input.cedula!, active: true, employed_from: input.employed_from!, employed_until: null })
    else if (input.action === 'update') Object.assign(accounts[0], { full_name: input.full_name, cedula: input.cedula, active: input.active, employed_from: input.employed_from, employed_until: input.employed_until })
    else if (input.action === 'disable') Object.assign(accounts[0], { active: false })
    else if (input.action === 'delete') accounts.splice(0)
    await route.fulfill({ json: { ok: true, id: teacherId } })
  })
  await signIn(page)
  await page.getByRole('link', { name: /^Docentes(?: \d+)?$/ }).click()
  const search = await page.getByLabel('Buscar por nombre o C.I.').boundingBox()
  const button = await page.getByRole('button', { name: 'Buscar', exact: true }).boundingBox()
  expect(search!.width).toBeGreaterThan(button!.width)
  expect(button!.x).toBeGreaterThan(search!.x + search!.width)
  expect(Math.abs(button!.y + button!.height - search!.y - search!.height)).toBeLessThan(2)
  await page.getByRole('button', { name: 'Crear docente', exact: true }).click()
  await page.getByLabel('Nombre completo', { exact: true }).fill('Docente de prueba')
  await page.getByLabel('C.I.', { exact: true }).fill('0000000009')
  await page.getByLabel('Nueva contraseña', { exact: true }).fill('FixturePassword2026!')
  await page.getByRole('button', { name: 'Guardar', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('Cambio guardado')
  await expect(page.getByRole('cell', { name: /^Docente de prueba 0000000009$/ })).toBeVisible()
  expect(requests[0]).toMatchObject({ action: 'create', cedula: '0000000009', employed_from: '2026-09-14' })
  await expect(page.getByRole('button', { name: 'Restablecer contraseña', exact: true })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Eliminar cuenta', exact: true })).toHaveCount(0)
  await page.getByRole('link', { name: 'Historial de Docente de prueba', exact: true }).click()
  await expect(page).toHaveURL(new RegExp(`/admin/docentes/${teacherId}$`))
  await expect(page.getByRole('heading', { name: 'Docente de prueba', exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Historial de asistencia' })).toBeVisible()
  await expect(page.getByLabel('Docente', { exact: true })).toHaveCount(0)
  await page.getByLabel('Desde', { exact: true }).fill('2026-09-01')
  await page.getByRole('button', { name: 'Consultar', exact: true }).click()
  await expect.poll(() => reports.at(-1)?.p_from).toBe('2026-09-01')
  expect(reports.every(request => request.p_id === teacherId && !('p_search' in request))).toBe(true)
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Docente de prueba', exact: true })).toBeVisible()
  await page.getByRole('link', { name: 'Volver a docentes' }).click()
  await page.getByRole('link', { name: 'Editar a Docente de prueba', exact: true }).click()
  await expect(page).toHaveURL(new RegExp(`/admin/docentes/${teacherId}/editar$`))
  await page.getByLabel('Nombre completo', { exact: true }).fill('Docente actualizado')
  await page.getByRole('button', { name: 'Guardar', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Docente actualizado', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Restablecer contraseña', exact: true }).click()
  await page.getByLabel('Nueva contraseña', { exact: true }).fill('SecondFixture2026!')
  await page.getByRole('button', { name: 'Guardar', exact: true }).click()
  await expect(page.getByLabel('Nueva contraseña', { exact: true })).toHaveCount(0)
  expect(requests[2]).toMatchObject({ action: 'reset-password', id: teacherId, password: 'SecondFixture2026!' })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: info.outputPath('teacher-details.png'), fullPage: true })
  await page.getByRole('link', { name: 'Volver a docentes' }).click()
  await page.getByRole('button', { name: 'Bloquear acceso de Docente actualizado', exact: true }).click()
  await expect(page.getByText(/Su historial de asistencia se conservará/)).toBeVisible()
  await page.getByRole('button', { name: 'Confirmar bloqueo' }).click()
  await expect(page.getByText('Bloqueado', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Bloquear acceso de Docente actualizado', exact: true })).toBeDisabled()
  expect(requests[3]).toEqual({ action: 'disable', id: teacherId })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: info.outputPath('teachers.png'), fullPage: true })
  await page.getByRole('link', { name: 'Editar a Docente actualizado', exact: true }).click()
  await page.getByLabel('Permitir acceso').check()
  await page.getByRole('button', { name: 'Guardar', exact: true }).click()
  await expect(page.getByText('Activo', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Eliminar cuenta', exact: true }).click()
  await expect(page.getByText(/Se eliminará la cuenta de inicio de sesión de forma permanente/)).toBeVisible()
  await page.getByRole('button', { name: 'Cancelar', exact: true }).click()
  expect(requests.some(request => request.action === 'delete')).toBe(false)
  await page.getByRole('button', { name: 'Eliminar cuenta', exact: true }).click()
  await page.getByRole('button', { name: 'Confirmar eliminación de cuenta' }).click()
  await expect(page).toHaveURL(/\/admin\/docentes$/)
  await expect(page.getByText('No hay docentes para esta búsqueda')).toBeVisible()
  expect(requests.at(-1)).toEqual({ action: 'delete', id: teacherId })
})

test('teacher cannot enter directory, details, or edit routes', async ({ page }) => {
  await mockBackend(page)
  await signIn(page)
  await expect(page).toHaveURL(/\/jornada$/)
  for (const path of ['/admin/docentes', `/admin/docentes/${teacherId}`, `/admin/docentes/${teacherId}/editar`]) {
    await page.goto(path)
    await expect(page).toHaveURL(/\/jornada$/)
    await expect(page.getByRole('button', { name: 'Crear docente', exact: true })).toHaveCount(0)
  }
})

test('missing teacher has a recoverable error and no account controls', async ({ page }) => {
  await mockBackend(page, { role: 'admin' })
  await page.route('**/rest/v1/rpc/admin_teacher', route => route.fulfill({ status: 400, json: { message: 'TEACHER_NOT_FOUND' } }))
  await signIn(page)
  await expect(page).toHaveURL(/\/admin$/)
  await page.goto(`/admin/docentes/${teacherId}/editar`)
  await expect(page.getByRole('alert')).toContainText('No se encontró la cuenta del docente')
  await expect(page.getByRole('link', { name: 'Volver a docentes' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Eliminar cuenta' })).toHaveCount(0)
})
