// Generates the browser RPC contract from a fresh schema's Postgres catalog.
// After hosted setup also run the Supabase CLI generation described in SETUP.md.
import { database } from '../tests/helpers/database.mjs'
import { mkdir, writeFile } from 'node:fs/promises'
const db = await database()
try {
  const { rows } = await db.query(`select p.proname as name, p.proargnames as names,
    array(select format_type(x,null) from unnest(p.proargtypes::oid[]) x) as types,
    p.pronargdefaults as defaults, format_type(p.prorettype,null) as returns
    from pg_proc p join pg_namespace n on n.oid=p.pronamespace
    where n.nspname='public' order by p.proname`)
  const ts = t => t.endsWith('[]') ? `${ts(t.slice(0,-2))}[]` : t === 'jsonb' ? 'Json' : t === 'void' ? 'undefined' : ['integer','bigint','smallint'].includes(t) ? 'number' : t === 'boolean' ? 'boolean' : 'string'
  const functions = rows.map(row => {
    const args = row.names?.map((name,i) => `${name}${i >= row.names.length-row.defaults ? '?' : ''}: ${ts(row.types[i])}`).join('; ') || ''
    return `      ${row.name}: { Args: ${args ? `{ ${args} }` : 'never'}; Returns: ${ts(row.returns)} }`
  }).join('\n')
  const { rows: columns } = await db.query(`select c.relname as table_name, a.attname as column_name,
    format_type(a.atttypid,a.atttypmod) as type, not a.attnotnull as nullable,
    a.atthasdef as has_default from pg_attribute a join pg_class c on c.oid=a.attrelid
    join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relkind='r'
    and a.attnum>0 and not a.attisdropped order by c.relname,a.attnum`)
  const tables = [...new Set(columns.map(c => c.table_name))].map(name => {
    const cols = columns.filter(c => c.table_name === name)
    const fields = mode => cols.map(c => `${c.column_name}${mode === 'Update' || (mode === 'Insert' && (c.nullable || c.has_default)) ? '?' : ''}: ${ts(c.type)}${c.nullable ? ' | null' : ''}`).join('; ')
    return `      ${name}: { Row: { ${fields('Row')} }; Insert: { ${fields('Insert')} }; Update: { ${fields('Update')} }; Relationships: [] }`
  }).join('\n')
  await mkdir('src/types',{recursive:true})
  await writeFile('src/types/database.ts', `// Generated by npm run db:types from migrations. Do not edit.\nexport type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]\nexport type Database = { public: {\n    Tables: {\n${tables}\n    }\n    Views: Record<string, never>\n    Functions: {\n${functions}\n    }\n    Enums: Record<string, never>\n    CompositeTypes: Record<string, never>\n} }\n`)
  console.log('Generated browser RPC types from the rebuilt Postgres schema.')
} finally { await db.close() }
